### ISSUE TITLE
'setn' is obsolete

### ISSUE THREAD

**Issue by beugnen** [Dyaxler/Altoholic_Vanilla#11]
Loading Wow Classic with this mod installed results in the following error upon login. 

(also occurs if you **/reload ui**)

>Date: 2020-01-04 08:51:51
ID: 1
Error occured in: Global
Count: 1
Message: ...face\AddOns\Altoholic\Libs\AceLibrary\AceLibrary.lua line 308:
   'setn' is obsolete
Debug:
   [C]: ?
   ...face\AddOns\Altoholic\Libs\AceLibrary\AceLibrary.lua:308:
      ...face\AddOns\Altoholic\Libs\AceLibrary\AceLibrary.lua:305
   ...face\AddOns\Altoholic\Libs\AceLibrary\AceLibrary.lua:546: Register()
   ...face\AddOns\Altoholic\Libs\AceLibrary\AceLibrary.lua:751: in main chunk
Locals:
(*temporary) = <table> {
 GetInstance = <function> defined @Interface\AddOns\Altoholic\Libs\AceLibrary\AceLibrary.lua:480
 IterateLibraries = <function> defined @Interface\AddOns\Altoholic\Libs\AceLibrary\AceLibrary.lua:699
 Register = <function> defined @Interface\AddOns\Altoholic\Libs\AceLibrary\AceLibrary.lua:525
 HasInstance = <function> defined @Interface\AddOns\Altoholic\Libs\AceLibrary\AceLibrary.lua:460
 IsNewVersion = <function> defined @Interface\AddOns\Altoholic\Libs\AceLibrary\AceLibrary.lua:443
 positions = <table> {
 }
 libs = <table> {
 }
}
(*temporary) = 0
`

**Comment by ghost** [comment]
This isnt for classic wow...

**Comment by beugnen** [comment]
> This isnt for classic wow...

Did you know that gerbils make good house pets?
