### ISSUE TITLE
AltoTooltip:OnEnter error

### ISSUE THREAD

**Issue by beugnen** [Dyaxler/Altoholic_Vanilla#12]
Hovering mouse over map icon results in:

> Date: 2020-01-04 08:55:30
ID: 72
Error occured in: Global
Count: 1
Message: [string "AltoTooltip:OnEnter"] line 1:
   Usage: AltoTooltip:SetOwner(region)
Debug:
   [C]: ?
   [C]: SetOwner()
   [string "*:OnEnter"]:1:
      [string "*:OnEnter"]:1
Locals:

**Comment by ghost** [comment]
this is not for classic wow, its for vanilla private servers 1.12.1

**Comment by beugnen** [comment]
> this is not for classic wow, its for vanilla private servers 1.12.1

We don't talk anymore.
