### ISSUE TITLE
Flakey mod doesnt work

### ISSUE THREAD

**Issue by beugnen** [Dyaxler/Altoholic_Vanilla#14]
Don't give up your day job because you guys suck at programming

this applies to all forks

**Comment by ghost** [comment]
You must suck at reading this is for 1.12.1 vanilla wow private servers not classic wow. LRN2READ.

**Comment by beugnen** [comment]
> You must suck at reading this is for 1.12.1 vanilla wow private servers not classic wow. LRN2READ.

What's your star sign?
