### ISSUE TITLE
Mail gets marked as unread even if all options regarding the mail are turned off

### ISSUE THREAD

**Issue by vehystrix** [Dyaxler/Altoholic_Vanilla#2]
Steps to reproduce:
1. Send mail to a character
2. Log in to the other character
3. Uncheck all options regarding mail ![see image](https://user-images.githubusercontent.com/7142781/35780336-fcc8dc7c-09d9-11e8-8560-3b690a56839c.png)
4. Open the ingame mailbox
5. Notice the newly sent mail is mark as read

**Comment by Dyaxler** [comment]
Thanks dude for putting it here. I'll get to it after AQ40.

**Comment by Dyaxler** [comment]
This issue was fixed in: https://github.com/Dyaxler/Altoholic_Vanilla/commit/ef982115440f35be6015fcd89b78a6bc07204a17
